from __future__ import annotations

from typing import Any, ContextManager, Protocol

from .models import ChatKind, ChatRecord, SessionRecord


class SessionRepository(Protocol):
    """Application-facing port for session persistence.

    The conversation application service depends on this contract; filesystem
    layout and locking remain infrastructure concerns of SessionStore.
    """

    def create_session(self, *, repo_root: str, title: str | None = None, session_id: str | None = None) -> SessionRecord: ...
    def ensure_session(self, *, repo_root: str, session_id: str | None = None, title: str | None = None) -> SessionRecord: ...
    def get_session(self, session_id: str) -> SessionRecord: ...
    def list_sessions(self) -> list[SessionRecord]: ...
    def close_session(self, session_id: str) -> SessionRecord: ...
    def create_chat(
        self, session_id: str, *, title: str, kind: ChatKind = ChatKind.STANDARD,
        make_active: bool = False, conversation_id: str | None = None,
    ) -> ChatRecord: ...
    def get_or_create_main_chat(self, session_id: str) -> ChatRecord: ...
    def get_chat(self, session_id: str, chat_id: str) -> ChatRecord: ...
    def list_chats(self, session_id: str, *, include_archived: bool = False) -> list[ChatRecord]: ...
    def select_chat(self, session_id: str, chat_id: str) -> SessionRecord: ...
    def archive_chat(self, session_id: str, chat_id: str) -> ChatRecord: ...
    def update_chat(self, session_id: str, chat_id: str, **updates: Any) -> ChatRecord: ...
    def append_request(self, session_id: str, chat_id: str, request_id: str) -> ChatRecord: ...
    def chat_operation_lock(self, session_id: str, chat_id: str) -> ContextManager[None]: ...
